# .binder/environment.yml
name: netmd-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Your core package
  - netmd

  # Core dependencies for Binder
  - python=3.10
  - jupyterlab
  - ipykernel